# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.2.0"

gem "github-pages", group: :jekyll_plugins

group :test do
  gem "html-proofer"
  gem "mdl"
  gem "rake"
  gem "webrick"
end
