name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: # on button click
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Merge upstream
        run: |
          git config --local user.email "131801252+merger-bot[bot]@users.noreply.github.com"
          git config --local user.name "merger-bot[bot]"
          
          git remote add upstream https://github.com/homebrew/brew.git
          git fetch upstream
          git fetch --tags upstream
          
          git merge --no-edit upstream/master
          git push
          git push --tags
